version: "3.8"

services:
  # This service builds the Hugo static site.
  hugo:
    image: klakegg/hugo:ext-alpine
    container_name: hugo_builder
    volumes:
      # Maps the current directory to /src in the container.
      - .:/src
    working_dir: /src
    command: >
      sh -c "hugo --minify --gc --enableGitInfo --destination /src/public"
    restart: "no"

  # This service serves the built static files via Nginx.
  hugo_server:
    image: nginx:1.27-alpine
    container_name: hugo_webserver
    volumes:
      # Mounts the 'public' folder that Hugo builds.
      - ./public:/usr/share/nginx/html:ro
      # Mounts the Nginx configuration file.
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - Shared
    depends_on:
      - hugo
    restart: unless-stopped

# Defines the external network used by Nginx Proxy Manager.
# Make sure this matches the network name your NPM uses.
networks:
  Shared:
    external: true
