version: "3.8"

services:
  # This service builds and serves the Hugo site using multi-stage Dockerfile
  hugo:
    build: .
    container_name: hugo_nginx
    networks:
      - Shared
    restart: unless-stopped

# Defines the external network used by Nginx Proxy Manager.
# Make sure this matches the network name your NPM uses.
networks:
  Shared:
    external: true
