version: "3.8"

services:
  # This service builds and serves the Hugo static site.
  hugo:
    image: klakegg/hugo:ext-alpine
    container_name: hugo_builder
    working_dir: /src
    command: ["hugo", "server", "--bind=0.0.0.0", "--port=80", "--baseURL=http://localhost", "--buildDrafts", "--buildFuture"]
    volumes:
      # Mount the repository files (pulled by Portainer GitOps)
      - .:/src
    networks:
      - Shared
    restart: unless-stopped

# Defines the external network used by Nginx Proxy Manager.
# Make sure this matches the network name your NPM uses.
networks:
  Shared:
    external: true
