backend:
  name: github
  repo: Ph-ill/dimis-corner
  branch: master

media_folder: static
public_folder: /

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/en/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Dimi"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
